apiVersion: v1
kind: Secret
metadata:
  name: {{ include "petclinic.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  QUARKUS_DATASOURCE_JDBC_URL: {{ include "petclinic.jdbc.url" . | b64enc }}
  QUARKUS_DATASOURCE_USERNAME: {{ .Values.deployment.datasource.username | b64enc }}
  QUARKUS_DATASOURCE_PASSWORD: {{ .Values.deployment.datasource.password | b64enc }} 
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJsYmFua2luZm9sb2dpc3RpeC5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoibGJhbmtpbmZvbG9naXN0aXgiLCJwYXNzd29yZCI6IkZ6VzQwSXhrT2E3b1lTQTNyL3QyMFM5MUhrRW5wNUNpWEMzU2UvK28weCtBQ1JDRTlYZnYiLCJhdXRoIjoiYkdKaGJtdHBibVp2Ykc5bmFYTjBhWGc2Um5wWE5EQkplR3RQWVRkdldWTkJNM0l2ZERJd1V6a3hTR3RGYm5BMVEybFlRek5UWlM4cmJ6QjRLMEZEVWtORk9WaG1kZz09In19fQ==
kind: Secret
metadata:
  name: registry
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
