---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - name: pgsql
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: quay.io/redhatdemo/openshift-pgsql12-primary:centos7
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "600m"
          ports:
            - name: tcp
              containerPort: 5432
          env:
            - name: PG_USER_PASSWORD
              value: developer
            - name: PG_USER_NAME
              value: developer
            - name: PG_DATABASE
              value: mydb
            - name: PG_NETWORK_MASK
              value: all
            - name: PG_MAX_CONNECTIONS
              value: "800"
            # 25% of the memory in mb
            - name: PG_SHARED_BUFFERS
              value: "250"
            - name: PG_WORK_MEM
              value: "250"
            # 75% of the memory in GB
            - name: PG_EFFECTIVE_CACHE_SIZE
              value: "6"
            - name: PG_EFFECTIVE_IO
              value: "128"
            # 20% of the Disk size
            - name: PG_MAX_WAL_SIZE
              value: "4"