apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "petclinic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    tbd: tbd
spec:
  endpoints:
  - honorLabels: true
    interval: 1m
    path: /metrics
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: petclinic