{{ if .Values.ingress.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  exportTo:
  - .
  hosts:
  {{- if .Values.debug.no_db }}
  - "sample-database.azure.com"
  {{- else }}
  - {{ .Values.deployment.datasource.db_host }}
  {{- end }}
  location: MESH_EXTERNAL
  ports:
  - name: jdbc
    number: 5432
    protocol: TCP
  resolution: NONE
{{ end }}
