name: Build-dictionary-image
 
on: workflow_dispatch #[push]
 
jobs:

  build_docker_img:

    runs-on: ubuntu-latest

    env:

      TAG: petclinic
      PAT: ${{ secrets.PAT }}
      USER: infologistix
      DOCKER_USER: palexus
      REGISTRY: ghcr.io
      VERSION: main
 
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: |
        chmod +x mvnw
        ./mvnw -B package --update-snapshots verify

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

   # - name: docker login
   #   env:
        #DOCKER_USER: ${{ secrets.DOCKER_USER }}   
   #     DOCKER_PASSWORD: $PAT # ${{ secrets.DOCKER_PASSWORD }}
      ## run command use for running linux command  
   #   run: |
   #     docker login ${{env.REGISTRY}} -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: docker build quarkus-petclinic-jvm
      run: |
        docker build --no-cache -f src/main/docker/Dockerfile.jvm -t ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }} .
        
    - name: docker push
      run: |
        docker push ${{env.REGISTRY}}/$USER/$TAG:${{ env.VERSION }}


 #   - name: Login to ghcr
 #     run: |
 #       echo $PAT | docker login ${{ env.REGISTRY}} -u $USER --password-stdin
 #       docker push ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
