name: workflow_pr

on:
  pull_request:
    branches: [ "main" ]

jobs:
  neuvector-scan:

    env:
      TAG: petclinic
      PAT: ${{ secrets.PAT }}
      USER: infologistix
      DOCKER_USER: palexus
      REGISTRY: ghcr.io
      VERSION: ${{ github.head_ref || github.ref_name }} 

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: |
        echo The Version is ${{ env.VERSION }}
        echo The Repo is ${{env.REGISTRY}}/$USER/$TAG
        chmod +x mvnw
        ./mvnw -B package --update-snapshots verify
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{env.REGISTRY}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: docker build quarkus-petclinic-jvm
      run: |
        docker build --no-cache -f src/main/docker/Dockerfile.jvm -t test .
        
    - name: Scan Image
      uses: neuvector/scan-action@main
      with:
        image-repository: test
        image-tag: latest
        min-high-cves-to-fail: "52"
        min-medium-cves-to-fail: "150"

  compliance-check:
    needs: [neuvector-scan]
    runs-on: ubuntu-latest
    steps:
    - name: compliance-check
      run: |
        echo "Hier werden compliance Regeln gecheckt"
