name: workflow_pr

on:
  pull_request:
    branches: [ "main" ]

jobs:
  neuvector-scan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: |
        chmod +x mvnw
        ./mvnw -B package --update-snapshots verify
        
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ## run command use for running linux command  
      run: |
        docker login lbankinfologistix.azurecr.io -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: docker build quarkus-petclinic-jvm
      run: |
        docker build --no-cache -f src/main/docker/Dockerfile.jvm -t lbankinfologistix.azurecr.io/quarkus-petclinic-jvm:latest .
        
    - name: Scan Image
      uses: neuvector/scan-action@main
      with:
        image-repository: lbankinfologistix.azurecr.io/quarkus-petclinic-jvm
        image-tag: latest
        min-high-cves-to-fail: "52"
        min-medium-cves-to-fail: "100"

  compliance-check:
    needs: [neuvector-scan]
    runs-on: ubuntu-latest
    steps:
    - name: compliance-check
      run: |
        echo "Hier werden compliance Regeln gecheckt"

