name: Deleting Postgres Server

#on: workflow_dispatch
on: delete

jobs:
  Update_fleet_repo:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.event.ref }}
      
    steps:
    - name: Set the environment variable
      run: |
        echo BRANCH=${{ github.event.ref }} >> $GITHUB_ENV
      
    - name: Checkout
      run: |
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.SSH_PRIVATE_KEY_FLEET }}'
        git clone git@github.com:infologistix/petclinic-fleet-gcp.git
        ls

    - name: Remove Branch and Commit Changes for Fleet repo
      run: |
        cd petclinic-fleet-gcp
        eval "$(ssh-agent -s)"
        ssh-add - <<< '${{ secrets.SSH_PRIVATE_KEY_FLEET }}'
        RandomID=$(cksum <<< ${GITHUB_REF##*/} | cut -f 1 -d ' ')
        echo "$RandomID github-actions[bot] pushes to Branch ${BRANCH}" 
        git config --local user.email "$RandomID+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git rm -r $BRANCH
        git commit -m "branch ${GITHUB_REF##*/} removed"
        git push


  Remove_Server:
    runs-on: ubuntu-latest
    
    env:
      BRANCH: ${{ github.event.ref }}
      
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY_APP }}
        persist-credentials: true
        repository: infologistix/petclinic-app-gcp

    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        credentials_json: ${{ secrets.GCLOUD_JSON }}

    - name: Delete Server
      run: |
        export NAME=postgres-$BRANCH
        gcloud sql instances delete $NAME \
          --project=$PROJECTS_ID


  Remove_Namespace:
    runs-on: ubuntu-latest
    needs: [Update_fleet_repo]
    
    steps:
    - name: Get Kubectl
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
        
    - name: Delete Namespace
      run: |
          NAMESPACE=$(echo ${{ github.event.ref }} | sed -e s/[\/_]/-/g | sed -e 's/\(.*\)/\L\1/g')
          if kubectl get namespace $NAMESPACE &> /dev/null; then 
            kubectl delete namespace $NAMESPACE
          else 
            echo "Namespace does not exist" 
          fi
